PREFIX basicfamily:        <http://example.com/vocabulary/basicfamily#>

SELECT DISTINCT ?person ?cousin
WHERE {
	?person basicfamily:cousin ?cousin .

	# ?person basicfamily:parents ?parent .
	# ?parent basicfamily:parents ?grandparent .
	# ?grandparent basicfamily:children ?uncleOrAunt .
	# FILTER(?uncleOrAunt != ?parent)
	# ?uncleOrAunt basicfamily:children ?cousin .
}
ORDER BY ?person ?cousin