PREFIX basicfamily:        <http://example.com/vocabulary/basicfamily#>

SELECT DISTINCT ?person (COUNT(?cousin) as ?cousins)
WHERE {
	?person a basicfamily:Person .
	OPTIONAL {
		?person basicfamily:cousin ?cousin
		
		# ?person basicfamily:parents ?parent .
		# ?parent basicfamily:parents ?grandparent .
		# ?grandparent basicfamily:children ?uncleOrAunt .
		# ?uncleOrAunt basicfamily:children ?cousin .
		# FILTER(?uncleOrAunt != ?parent)
	}
}
GROUP BY ?person
ORDER BY ?person